### ISSUE TITLE
Create all database-tables in django

### ISSUE THREAD

**Issue by IsakLundstrom** [IsakLundstrom/M7011E_Project#7]
Create all database-tables/models in django and migrate them to the database

**Comment by FlorBl** [comment]
Inside your Terminal, cd to:
**\M7011E_Project\backend**      --->**NOT** \M7011E_Project\backend\backend

When your are inside that directory, in Terminal, type the following command:
**python manage.py makemigrations**

After, that command is completed, type the following command:
**python manage.py migrate**

Now you can go to **\M7011E_Project\backend\courses\migrations**
You should see a new filed that has been created called: **0001_initial.py**
Voila!
![1](https://user-images.githubusercontent.com/56225530/202626115-cb0fb492-3591-419d-bd4d-1be267459736.jpg)
![2](https://user-images.githubusercontent.com/56225530/202626119-79eaea5e-982d-4c34-85c3-1b05a94e75b5.jpg)

**Comment by IsakLundstrom** [comment]
This is fine but this is a COURSE at a UNIVERSITY we want to do it alone, thank you. We need to have the repo public for the examiner so he can see it
